apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-world
spec:
  params:
    - name: GL_USER
      type: string
    - name: GL_REPO
      type: string
    - name: GL_REFNAME
      type: string
    - name: GL_OLDREV
      type: string
    - name: GL_NEWREV
      type: string
  workspaces:
    - name: source # for source code
    - name: ssh-credentials  # Store SSH keys
    - name: ssh-config  # Store SSH setup
    - name: kubeconfig
  steps:
    - name: setup-ssh
      image: containers.gingersociety.org/secure-git-task-runner:latest
      script: |
        #!/bin/sh

        /usr/local/bin/configurator.sh
        
        git config --global init.defaultBranch main
        git clone git@source.gingersociety.org:$(params.GL_REPO) /workspace/source/$(params.GL_REPO)
        echo "Repository cloned successfully."
        cd /workspace/source/$(params.GL_REPO)
        ls -la .tekton
        
        cp -r /workspace/kubeconfig /keys


        echo "🔹 Processing Tekton tasks..."
        NAMESPACE="tasks-$(params.GL_REPO)"
        echo "📌 Using namespace: $NAMESPACE"

        echo "🔹 Setting KUBECONFIG..."
        export KUBECONFIG=/workspace/kubeconfig/kubeconfig.gingersociety.prod.yml

        # Ensure namespace exists
        kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$NAMESPACE"

        DOCKER_REGISTRY="containers.gingersociety.org"
        DOCKER_USERNAME="myuser"
        DOCKER_PASSWORD="mypassword"
        DOCKER_EMAIL="admin@gingersociety.org"
        RUNNER_KEY="/workspace/ssh-credentials/id_ed25519"
        ENV_FILE="secrets.env"

        echo "📝 Creating secrets.env file..."
        cat <<EOF > "$ENV_FILE"
        GINGER_TOKEN=token
        DOCKER_USERNAME=myuser
        DOCKER_PASSWORD=mypassword
        EOF


        echo "🔧 Target namespace: $NAMESPACE"
        kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create namespace "$NAMESPACE"

        echo "📦 Creating PVC: buildah-cache..."
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: buildah-cache
          namespace: $NAMESPACE
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
          storageClassName: standard
        EOF

        echo "🗄️ Creating PV: ${NAMESPACE}-pv..."
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: ${NAMESPACE}-pv
        spec:
          capacity:
            storage: 10Gi
          accessModes:
            - ReadWriteMany
          persistentVolumeReclaimPolicy: Retain
          storageClassName: nfs-storage-class 
          nfs:
            path: /srv/nfs/gitolite
            server: 192.168.49.1
        EOF

        echo "📦 Creating PVC: ${NAMESPACE}-pvc..."
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: ${NAMESPACE}-pvc
          namespace: $NAMESPACE
        spec:
          volumeName: ${NAMESPACE}-pv
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
          storageClassName: nfs-storage-class
        EOF

        echo "👤 Creating ServiceAccount: tekton-registry-access..."
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: tekton-registry-access
          namespace: $NAMESPACE
        secrets:
          - name: regcred
        imagePullSecrets:
          - name: regcred
        EOF

        echo "🔐 Creating Docker registry secret: regcred..."
        kubectl create secret docker-registry regcred \
          --docker-server="$DOCKER_REGISTRY" \
          --docker-username="$DOCKER_USERNAME" \
          --docker-password="$DOCKER_PASSWORD" \
          --docker-email="$DOCKER_EMAIL" \
          -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

        echo "🔐 Creating pipeline secrets from $ENV_FILE..."
        kubectl create secret generic pipeline-secrets-secret \
          --from-env-file="$ENV_FILE" \
          -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

        echo "🔐 Creating SSH private key secret from $RUNNER_KEY..."
        kubectl create secret generic ssh-private-key \
          --from-file=id_ed25519="$RUNNER_KEY" \
          -n "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

        echo "✅ All resources created for namespace: $NAMESPACE"

       

        EXISTING_TASKS=$(ls /workspace/source/$(params.GL_REPO)/.tekton | grep -E '\.yml$' | sed 's/.yml$//')
        CURRENT_TASKS=$(kubectl get tasks -n "$NAMESPACE" -o=jsonpath='{.items[*].metadata.name}')

        for task in $CURRENT_TASKS; do
          if ! echo "$EXISTING_TASKS" | grep -q "$task"; then
            echo "🗑 Deleting stale task: $task"
            kubectl delete task "$task" -n "$NAMESPACE"
          fi
        done
        echo "✅ Stale tasks removed."

        # Apply all YAML files in .tekton from the shared workspace
        for file in /workspace/source/$(params.GL_REPO)/.tekton/*.yml; do
          if [ -f "$file" ]; then
            echo "📌 Applying: $file"
            kubectl apply -f "$file" -n "$NAMESPACE"
            # Extract the task name from the applied file using kubectl
            TASK_NAME=$(kubectl get -f "$file" -o jsonpath='{.metadata.name}')
            echo "TASK_NAME : ${TASK_NAME}"
            # Wait briefly to ensure task registration
            sleep 2

            # Retrieve the trigger branch annotation from the applied task
            TRIGGER_BRANCHES=$(kubectl get task "$TASK_NAME" -n "$NAMESPACE" -o jsonpath='{.metadata.annotations.x-ginger-task-trigger-branch}')
            
            echo "🔍 Task: $TASK_NAME | Retrieved trigger branches: $TRIGGER_BRANCHES"
            CURRENT_BRANCH="$(params.GL_REFNAME)"  # Get the current branch reference
            
            # Check if the branch exists in the trigger list
            if echo "$TRIGGER_BRANCHES" | jq -e ".[] | select(. == \"$CURRENT_BRANCH\")" > /dev/null; then
              echo "🚀 Branch $CURRENT_BRANCH matches trigger list. Creating TaskRun for $TASK_NAME..."

              # Generate TaskRun YAML dynamically
              cat <<EOF > "/workspace/source/taskrun-$TASK_NAME.yaml"
          apiVersion: tekton.dev/v1beta1
          kind: TaskRun
          metadata:
            generateName: ${TASK_NAME}-run-
            namespace: $NAMESPACE
          spec:
            serviceAccountName: tekton-registry-access
            taskRef:
              name: $TASK_NAME
            workspaces:
              - name: source
                emptyDir: {}  # Temporary in-memory storage
              - name: ssh-credentials
                secret:
                  secretName: ssh-private-key  # Reference to your SSH private key secret
              - name: ssh-config
                emptyDir: {}  # Shared space for SSH setup
              - name: buildah-cache
                persistentVolumeClaim:
                  claimName: buildah-cache
              - name: kubeconfig  # Mount kubeconfig from existing PVC
                persistentVolumeClaim:
                  claimName: $NAMESPACE-pvc
                subPath: kubeconfigs  # Use the 'kubeconfigs' sub-directory
              - name: pipeline-secrets
                secret:
                  secretName: pipeline-secrets-secret
        EOF

              # Apply the TaskRun
              less /workspace/source/taskrun-$TASK_NAME.yaml
              kubectl create -f "/workspace/source/taskrun-$TASK_NAME.yaml"
            else
              echo "⚠️ Branch $CURRENT_BRANCH is NOT in the trigger list for $TASK_NAME. Skipping TaskRun."
            fi
          fi
        done
        echo "✅ Tekton tasks applied."

        

        
       