apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: trigger-run-
spec:
  taskRef:
    name: hello-world
  workspaces:
    - name: source
      emptyDir: {}  # Temporary in-memory storage
    - name: ssh-credentials
      secret:
        secretName: ssh-private-key  # Reference to your SSH private key secret
    - name: ssh-config
      emptyDir: {}  # Shared space for SSH setup
    - name: kubeconfig  # Mount kubeconfig from existing PVC
      persistentVolumeClaim:
        claimName: gitolite-pvc
      subPath: kubeconfigs  # Use the 'kubeconfigs' sub-directory
  params:
    - name: GL_USER
      value: "git"
    - name: GL_REPO
      value: "academy-database"
    - name: GL_REFNAME
      value: "refs/heads/main"
    - name: GL_OLDREV
      value: ""
    - name: GL_NEWREV
      value: ""
