apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
data:
  config.yaml: |
    storage: /verdaccio/storage
    web:
      title: "GingerSociety Artifactory"
      favicon: https://www.gingersociety.org/ginger_icon.ico
    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/
    packages:
      '@gingersociety/*':         
        access: $all
        publish: $all

      '@*/*':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
      '**':
        access: $authenticated
        publish: $authenticated
        proxy: npmjs
    server:
      trustProxy: "10.0.0.0/8"
    experiments:
      trust_proxy: true      
    log:
      type: stdout
      format: pretty
      level: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    snapshot.gingersociety.org/enabled: "true"
    volume.kubernetes.io/selected-node: "artifactory-control-plane"
  name: verdaccio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
        - name: verdaccio
          image: gingersociety/artifactory-npm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4873
          env:
            - name: VERDACCIO_PUBLIC_URL
              value: "https://npm.gingersociety.org"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: verdaccio-secrets   # secret name
                  key: JWT_SECRET_KEY       # key inside the secret
          volumeMounts:
            - name: storage
              mountPath: /verdaccio/storage
            - name: config        
              mountPath: /verdaccio/conf/config.yaml
              subPath: config.yaml
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: verdaccio-pvc
        - name: config            
          configMap:
            name: verdaccio-config

---
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
spec:
  selector:
    app: verdaccio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4873
