apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: parallel-test-
spec:
  pipelineRef:
    name: parallel-ci-pipeline
  workspaces:
    - name: shared-source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 500Mi