apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pypiserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pypiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pypiserver
  template:
    metadata:
      labels:
        app: pypiserver
    spec:
      containers:
        - name: pypiserver
          image: pypiserver/pypiserver:latest
          args: ["run"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data/packages
              name: package-storage
      volumes:
        - name: package-storage
          persistentVolumeClaim:
            claimName: pypiserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pypiserver
spec:
  selector:
    app: pypiserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
