apiVersion: v1
kind: Service
metadata:
  name: ginger-db-test-env-service
  labels:
    app: ginger-db-test-env
spec:
  selector:
    app: ginger-db-test-env
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000