apiVersion: v1
kind: Secret
metadata:
  name: tekton-sidekick-service-api-secrets
  namespace: tekton-pipelines
type: Opaque
stringData:
  ISC_SECRET: {{TEKTON_SIDEKICK.ISC_SECRET}}
  ROCKET_SECRET_KEY: {{shared.ROCKET_SECRET_KEY}}