# registry-auth-secret (your existing one - only if not already created)
apiVersion: v1
kind: Secret
metadata:
  name: mirror-registry-auth-secret
type: Opaque
stringData:
  username:  {{DOCKER.MIRROR_SRC_USERNAME}}
  password:  {{DOCKER.MIRROR_SRC_PASSWORD}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mirror-dockerhub-creds
type: Opaque
stringData:
  username:  {{DOCKER.MIRROR_DEST_USERNAME}}
  password:  {{DOCKER.MIRROR_DEST_PASSWORD}}
