apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-auth
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | b64enc }}
  password: {{ .Values.rabbitmq.auth.password | b64enc }}

  # Management UI URL
  url: {{ printf "http://%s:%s@localhost:%d" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Values.rabbitmq.service.managementPort | b64enc }}

  # ✅ AMQP URL
  amqp_url: {{ printf "amqp://%s:%s@%s:%v/%%2f" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password (include "rabbitmq.fullname" .) .Values.rabbitmq.service.amqpPort | b64enc }}