apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  selector:
    app: {{ include "rabbitmq.name" . }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
    - name: metrics
      port: {{ .Values.rabbitmq.service.metricsPort }}
      targetPort: {{ .Values.rabbitmq.service.metricsPort }}