apiVersion: v1
kind: Service
metadata:
  name: iam-admin-frontend-service
  labels:
    app: iam-admin-frontend-app
spec:
  selector:
    app: iam-admin-frontend-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80