apiVersion: v1
kind: Secret
metadata:
  name: ginger-kube-api-secrets
type: Opaque
stringData:
  ISC_SECRET: {{GINGER_KUBE.ISC_SECRET}}
  ROCKET_SECRET_KEY: {{shared.ROCKET_SECRET_KEY}}
  DATABASE_URL: {{GINGER_KUBE.DB_URL}}