apiVersion: v1
kind: Service
metadata:
  name: gingerkubeservice-service
  labels:
    app: gingerkubeservice
spec:
  selector:
    app: gingerkubeservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
