apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-gen-service
  labels:
    app: schema-gen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-gen-service
  template:
    metadata:
      labels:
        app: schema-gen-service
    spec:
      containers:
        - name: schema-gen-service
          image: gingersociety/db-compose-runtime-prod:latest
          command: ["/app/run.sh"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: HOST
              value: "db-compose-test-env.gingersociety.org"
            - name: APP_ID
              value: "db-compose-test-env"
