apiVersion: v1
kind: Secret
metadata:
  name: metadata-service-api-secrets
type: Opaque
stringData:
  ISC_SECRET: {{METADATA.ISC_SECRET}}
  ROCKET_SECRET_KEY: {{shared.ROCKET_SECRET_KEY}}
  DATABASE_URL: {{METADATA.DB_URL}}