apiVersion: v1
kind: Service
metadata:
  name: metadataservice-service
  labels:
    app: metadataservice
spec:
  selector:
    app: metadataservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
