apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-auth
type: Opaque
data:
  password: {{ .Values.redis.auth.password | b64enc }}

  # Redis URL with auth (for apps connecting to Redis)
  url: {{ printf "redis://:%s@%s:%v" .Values.redis.auth.password (include "redis.fullname" .) .Values.redis.service.redisPort | b64enc }}

  # Redis exporter URL (used internally by the sidecar)
  exporter_url: {{ printf "redis://:%s@localhost:%v" .Values.redis.auth.password .Values.redis.service.redisPort | b64enc }}
