apiVersion: v1
kind: Secret
metadata:
  name: gitolite-admin-key
type: Opaque
stringData:
  gh_pat: "{{GH_MIRROR.PAT}}"
data:
  admin_key.pub: "{{GITOLITE.ADMIN_KEY_PUB | b64encode}}"
  admin_key: "{{GITOLITE.ADMIN_KEY | b64encode}}"
  gh_ssh_key: "{{GH_MIRROR.SSH_KEY | b64encode}}"