# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitolite-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/gitolite   # host path where data will live
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    snapshot.gingersociety.org/enabled: "true"
    volume.kubernetes.io/selected-node: "artifactory-control-plane"
  name: gitolite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi