# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service-api-deployment
  labels:
    app: metadata-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service-api
  template:
    metadata:
      labels:
        app: metadata-service-api
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:latest
          command:
          - "sh"
          - "-c"
          - |
            echo "Checking PostgreSQL readiness..."
            until pg_isready -h dc01-pg-db-1-postgresql.default.svc.cluster.local -p 5432 -U postgres; do 
              echo "Waiting for DB to be ready..."
              sleep 5; 
            done
            echo "Database is ready!"
      containers:
      - name: metadata-service-api
        image: gingersociety/metadata-service-api-stage:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:pass@dc01-pg-db-1-postgresql:5432/metadata"
        - name: REDIS_URI
          value: "redis://redis-service:6379"
        - name: ROCKET_SECRET_KEY
          value: "secret"
        - name: ROCKET_ADDRESS
          value: "0.0.0.0"
        - name: ROCKET_PORT
          value: "8000"
        - name: JWT_SECRET
          value: "1234"
        - name: ISC_SECRET
          value: "supersecret"
