apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcs-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: api.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /example
            pathType: Prefix
            backend:
              service:
                name: example-service
                port:
                  number: 80

          - path: /iam
            pathType: Prefix
            backend:
              service:
                name: iamservice-service
                port:
                  number: 80

          - path: /metadata
            pathType: Prefix
            backend:
              service:
                name: metadataservice-service
                port:
                  number: 80

          - path: /iam-admin
            pathType: Prefix
            backend:
              service:
                name: iamadminservice-service
                port:
                  number: 80

          - path: /notification
            pathType: Prefix
            backend:
              service:
                name: notificationservice-service
                port:
                  number: 80

    - host: iam.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iam-frontend-users-service
                port:
                  number: 80

    - host: iam-admin.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iam-admin-fe-service
                port:
                  number: 80
      
    - host: {{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-service
                port:
                  number: 80

    - host: k8-prod-dashboard.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-auth-proxy
                port:
                  number: 80

    - host: db-compose-test-env.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: schema-gen-service-service
                port:
                  number: 80

    - host: dev-portal.{{HOSTING_FQDN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-portal-service
                port:
                  number: 80