apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            autoindex on;  # Enable directory listing
            autoindex_exact_size off;
            autoindex_format html;
            autoindex_localtime on;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-image-service
  labels:
    app: static-image-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-image-service
  template:
    metadata:
      labels:
        app: static-image-service
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: static-images-storage
          mountPath: /usr/share/nginx/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
      volumes:
      - name: static-images-storage
        persistentVolumeClaim:
          claimName: images
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: static-image-service
  labels:
    app: static-image-service
spec:
  selector:
    app: static-image-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
