apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/mnt/data/images"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: images-pv
  storageClassName: standard