apiVersion: v1
kind: Service
metadata:
  name: tekton-dashboard-proxy
  namespace: default  # ✅ Proxy service in `default`
spec:
  type: ExternalName
  externalName: tekton-dashboard.tekton-pipelines.svc.cluster.local
  ports:
    - port: 9097
      targetPort: 9097
