apiVersion: v1
kind: Secret
metadata:
  name: ses-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{NOTIFICATION.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: {{NOTIFICATION.AWS_SECRET_ACCESS_KEY}}

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  JWT_SECRET: "{{shared.JWT_SECRET_KEY}}"