apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-db-runtime
  labels:
    app: iam-db-runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam-db-runtime
  template:
    metadata:
      labels:
        app: iam-db-runtime
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-db
          image: postgres:latest
          command:
          - "sh"
          - "-c"
          - |
            echo "Checking PostgreSQL readiness..."
            until pg_isready -h dc01-pg-db-1-postgresql.default.svc.cluster.local -p 5432 -U postgres; do 
              echo "Waiting for DB to be ready..."
              sleep 5; 
            done
            echo "Database is ready!"
      containers:
        - name: iam-db-runtime
          image: gingersociety/iam-db-runtime-prod:latest
          ports:
            - containerPort: 8000
          env:
            - name: HOST
              value: "iam-db.gingersociety.org"
            - name: APP_ID
              value: "iam-db-runtime"
            - name: DB_NAME
              value: "iam"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "jamesbond"
            - name: DB_HOST
              value: "dc01-pg-db-1-postgresql"
            - name: DB_PORT
              value: "5432"
        - name: backup-sidecar
          image: containers.gingersociety.org/gingersociety/pg-backup-to-aws-helper
          env:
            - name: PG_HOST
              value: "dc01-pg-db-1-postgresql"
            - name: PG_PORT
              value: "5432"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              value: "jamesbond"
            - name: PG_DATABASE
              value: "iam"
            - name: S3_BUCKET
              value: "rackmint-db-backups"
            - name: AWS_ACCESS_KEY_ID
              value: "ACCESS_KEY"
            - name: AWS_SECRET_ACCESS_KEY
              value: "SECRET"
            - name: AWS_REGION
              value: "ap-south-1"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo "Starting DB backup loop..."
              export PGPASSWORD=$PG_PASSWORD
              while true; do
                echo "Creating database dump at $(date)..."
                FILENAME="backup_$(date +%Y-%m-%dT%H-%M-%S).sql.gz"
                pg_dump -h $PG_HOST -p $PG_PORT -U $PG_USER -d $PG_DATABASE | gzip > /tmp/$FILENAME

                echo "Uploading $FILENAME to S3..."
                aws s3 cp /tmp/$FILENAME s3://$S3_BUCKET/$PG_DATABASE/$FILENAME --region $AWS_REGION

                echo "Cleaning up local file..."
                rm /tmp/$FILENAME

                echo "Sleeping for 6 hours..."
                sleep 21600
              done
