FROM rust:1-slim-bullseye

RUN apt update
RUN apt install curl zsh nano docker.io pkg-config libssl-dev gcc-mingw-w64-x86-64 libpq-dev -y
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" -y

RUN rustup target add x86_64-pc-windows-gnu
RUN rustup component add rustfmt
RUN echo "zsh" >> ~/.bashrc


# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
RUN apt install -y nodejs

# Install Java
RUN apt install -y default-jdk

# Install OpenAPI Generator CLI globally
RUN npm install @openapitools/openapi-generator-cli -g

RUN openapi-generator-cli version

RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-all-clis.sh)"