architecture: standalone

primary:
  persistence:
    size: 4Gi

  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 1

  configuration: |-
    max_connections = 40
    shared_buffers = 128MB
    max_wal_size = 512MB