apiVersion: v1
kind: Service
metadata:
  name: gitolite
spec:
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  selector:
    app: gitolite
  type: NodePort  # Change to LoadBalancer if using cloud
