apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-portal-config
data:
  config.json: |
    {
      "IAMService": "https://api.{{HOSTING_FQDN}}/iam",
      "MetadataService": "https://api.{{HOSTING_FQDN}}/metadata",
      "NotificationService": "https://api.{{HOSTING_FQDN}}",
      "GINGER_SOCIETY_IAM_FRONTEND_USERS": "https://iam.{{HOSTING_FQDN}}",
      "GINGER_SOCIETY_NOTIFICATIONSERVICE_WS": "wss://api.{{HOSTING_FQDN}}/notification"
    }