apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter:latest
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://user:pass@server:port/db-name?sslmode=require" # Update with your credentials , db name can be one of the DB names
        ports:
        - containerPort: 9187 # Default port for PostgreSQL exporter

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter