# Prometheus Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
# Prometheus ConfigMap with Service Scraping Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "metadata-service-api"
        metrics_path: /metadata/metrics
        static_configs:
          - targets: ["metadata-service-api-service:80"]

      - job_name: "iam-service-api"
        metrics_path: /iam/metrics
        static_configs:
          - targets: ["iam-service-api-service:80"]

      - job_name: "notification-service"
        metrics_path: /notification/metrics
        static_configs:
          - targets: ["notification-service-service:80"]

      - job_name: "rabbitmq-service"
        metrics_path: /metrics
        static_configs:
          - targets: ["rabbitmq-service:9419"]
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-service:9121']
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter-service:9187']


---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30090
  selector:
    app: prometheus