apiVersion: v1
kind: Service
metadata:
  name: dev-portal-frontend-service
  labels:
    app: dev-portal-frontend-app
spec:
  selector:
    app: dev-portal-frontend-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80