apiVersion: v1
kind: Service
metadata:
  name: iam-frontend-users-service
  labels:
    app: iam-frontend-users
spec:
  selector:
    app: iam-frontend-users
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80