apiVersion: v1
kind: Secret
metadata:
  name: iamadminservice-secrets
type: Opaque
stringData:
  ISC_SECRET: {{IAM_ADMIN.ISC_SECRET}}
  ROCKET_SECRET_KEY: {{shared.ROCKET_SECRET_KEY}}
  DATABASE_URL: {{IAM_ADMIN.DB_URL}}