apiVersion: v1
kind: PersistentVolume
metadata:
  name: ginger-bucket-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ginger-bucket   # host path where uploaded files will live
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    snapshot.gingersociety.org/enabled: "true"
    volume.kubernetes.io/selected-node: "artifactory-control-plane"
  name: ginger-bucket-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi