apiVersion: v1
kind: Service
metadata:
  name: ginger-bucket-service
  labels:
    app: ginger-bucket
spec:
  selector:
    app: ginger-bucket
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080