apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdaccio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
    spec:
      containers:
        - name: verdaccio
          image: verdaccio/verdaccio:latest
          ports:
            - containerPort: 4873
          env:
            - name: VERDACCIO_PUBLIC_URL
              value: "https://npm.gingersociety.org"
          volumeMounts:
            - name: storage
              mountPath: /verdaccio/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: verdaccio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
spec:
  selector:
    app: verdaccio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4873
