apiVersion: v1
kind: Secret
metadata:
  name: iam-service-api-secrets
type: Opaque
stringData:
  ISC_SECRET: "{{IAM.ISC_SECRET}}"
  ROCKET_SECRET_KEY: "{{shared.ROCKET_SECRET_KEY}}"
  DATABASE_URL: "{{IAM.DB_URL}}"
  DOCKER_TOKEN_ISSUER: "{{DOCKER.TOKEN_ISSUER}}"
data:
  DOCKER_REGISTRY_PRIVATE_KEY: "{{DOCKER.REGISTRY_AUTH_PRIVATE_KEY | b64encode}}"

---
apiVersion: v1
kind: Secret
metadata:
  name: iam-git-ssh-ca-secret
type: Opaque
data:
  ca_key: "{{GITOLITE.CA_KEY | b64encode}}"