apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificationservice
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationservice
          image: gingersociety/notification-service-stage:latest
          ports:
            - containerPort: 3030

          env:
            # ✅ AMQP from RabbitMQ Helm secret
            - name: AMPQ_URI
              valueFrom:
                secretKeyRef:
                  name: changi-rabbitmq-auth
                  key: amqp_url

            # ✅ AWS creds from SES secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_REGION
              value: "ap-south-1"
            
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: estonia-redis-auth
                  key: url
            
            - name: REDIS_PUBSUB_URI
              valueFrom:
                secretKeyRef:
                  name: estonia-redis-auth
                  key: url