apiVersion: v1
kind: Service
metadata:
  name: notificationservice-service
  labels:
    app: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030
