apiVersion: v1
kind: Service
metadata:
  name: iam-admin-service-api-service
  labels:
    app: iam-admin-service-api
spec:
  selector:
    app: iam-admin-service-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
